### PR TITLE
The visualize_cut_plane() function has been modified to display image captions.

### PR DESCRIPTION
**Pull request by tatesnow**
**Feature or improvement description**

The visualize_cut_plane() function has been modified to display image captions.
**Related issue, if one exists**

**Impacted areas of the software**

visualize_cut_plane() and example_01_basic_adjustments.py
**Additional supporting information**

**Test results, if applicable**

yes

### CODE REVIEW

**Comment by tatesnow** [comment]
Why is there no response to this one?

**Comment by rafmudaf** [comment]
@paulf81 @bayc it looks like this pull request is primarily around passing a title through to the figure. The other changes are cleaning up unused imports.

**Comment by rafmudaf** [comment]
Also FYI this is a pull request to the main branch. Should it go to develop instead?

**Comment by paulf81** [comment]
hi @rafmudaf agree to develop to go to main in next version, I checked the file changes and looks good to me

**Comment by rafmudaf** [comment]
@tatesnow are #237 and this pull request meant to be the same? If so, please close one and we'll review and merge the one you leave open.

**Comment by tatesnow** [comment]
@rafmudaf okay! I have closed #237 ,thank you very much!

**Review by rafmudaf — APPROVED** [review]

**Pull request merged**
