### PR TITLE
Add minimum_ws and maximum_ws to yaw optimizer codes

### PR DESCRIPTION
**Pull request by Bartdoekemeijer**
**Feature or improvement description**
Add `minimum_ws` and `maximum_ws` options to the yaw optimization codes. If the specified wind speed falls out of these bounds, the optimization is skipped and the baseline yaw angles are specified as the optimal.

**Related issue, if one exists**
@ejsimley raised this issue in a personal conversation earlier today.

**Impacted areas of the software**
Controls optimization module.

**Additional supporting information**
N/A

**Test results, if applicable**
I have tested this on my own machine, and it works successfully for `yaw_optimizer_wind_rose_serial` and `yaw_optimizer_wind_rose_multiprocessing`. Take this example, where I specify `minimum_ws=8.5` while `ws_array` is an array with all `8.0` values:

```
Using 8 cores for parallel processing.
Finding optimal yaw angles in FLORIS...
=====================================================
Optimizing wake redirection control in parallel using multiprocessing...
Number of wind conditions to optimize =  12
=====================================================
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 0.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 30.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 60.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 90.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 120.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 150.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
   Skipping optimization: outside of wind speed bounds.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 180.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 240.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 210.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 270.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 300.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
   Skipping optimization: outside of wind speed bounds.
   Skipping optimization: outside of wind speed bounds.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 330.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
==========================================
Total Power Gain = 
Case [0]: wd = 0.00 deg. Gain: 0.000 %
Case [1]: wd = 30.00 deg. Gain: 0.000 %
Case [2]: wd = 60.00 deg. Gain: 0.000 %
Case [3]: wd = 90.00 deg. Gain: 0.000 %
Case [4]: wd = 120.00 deg. Gain: 0.000 %
Case [5]: wd = 150.00 deg. Gain: 0.000 %
Case [6]: wd = 180.00 deg. Gain: 0.000 %
Case [7]: wd = 210.00 deg. Gain: 0.000 %
Case [8]: wd = 240.00 deg. Gain: 0.000 %
Case [9]: wd = 270.00 deg. Gain: 0.000 %
Case [10]: wd = 300.00 deg. Gain: 0.000 %
Case [11]: wd = 330.00 deg. Gain: 0.000 %
==========================================
==========================================
Total time spent: 0.72 s
==========================================
```

and with `minimum_ws=7.5`:
```
Using 8 cores for parallel processing.
Finding optimal yaw angles in FLORIS...
=====================================================
Optimizing wake redirection control in parallel using multiprocessing...
Number of wind conditions to optimize =  12
=====================================================
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 0.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 30.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 60.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 90.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 120.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 150.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 180.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 210.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 240.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 270.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 300.00 deg turbulence intensity = 0.060.
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0
            Iterations: 1
            Function evaluations: 3
            Gradient evaluations: 1
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 330.00 deg turbulence intensity = 0.060.
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0187704706878338
            Iterations: 4
            Function evaluations: 12
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.088010003776945
            Iterations: 1
            Function evaluations: 4
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0880100037769445
            Iterations: 1
            Function evaluations: 4
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0
            Iterations: 3
            Function evaluations: 9
            Gradient evaluations: 3
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0187704706878347
            Iterations: 4
            Function evaluations: 12
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.1643633813918597
            Iterations: 4
            Function evaluations: 20
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.164341078402613
            Iterations: 4
            Function evaluations: 20
            Gradient evaluations: 4
==========================================
Total Power Gain = 
Case [0]: wd = 0.00 deg. Gain: 8.801 %
Case [1]: wd = 30.00 deg. Gain: 0.000 %
Case [2]: wd = 60.00 deg. Gain: 1.877 %
Case [3]: wd = 90.00 deg. Gain: 16.436 %
Case [4]: wd = 120.00 deg. Gain: 0.000 %
Case [5]: wd = 150.00 deg. Gain: 0.000 %
Case [6]: wd = 180.00 deg. Gain: 8.801 %
Case [7]: wd = 210.00 deg. Gain: 0.000 %
Case [8]: wd = 240.00 deg. Gain: 1.877 %
Case [9]: wd = 270.00 deg. Gain: 16.434 %
Case [10]: wd = 300.00 deg. Gain: 0.000 %
Case [11]: wd = 330.00 deg. Gain: 0.000 %
==========================================
==========================================
Total time spent: 2.58 s
==========================================
```

and with `minimum_ws=7.5`, `maximum_ws=20.0` and `ws_array = [8.0, 8.0, 6.0, 8.0, 8.0, 26.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]`:
```
Using 8 cores for parallel processing.
Finding optimal yaw angles in FLORIS...
=====================================================
Optimizing wake redirection control in parallel using multiprocessing...
Number of wind conditions to optimize =  12
=====================================================
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 0.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 30.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 6.00 m/s,  wind direction = 60.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 90.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 120.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 26.00 m/s,  wind direction = 150.00 deg turbulence intensity = 0.060.
/home/bartdoekemeijer/python_scripts/floris/floris/simulation/wake_deflection/gauss.py:209: RuntimeWarning: invalid value encountered in sqrt
  ln_deltaNum = (1.6 + np.sqrt(M0)) * (
/home/bartdoekemeijer/python_scripts/floris/floris/simulation/wake_deflection/gauss.py:210: RuntimeWarning: invalid value encountered in sqrt
  1.6 * np.sqrt(sigma_y * sigma_z / (sigma_y0 * sigma_z0)) - np.sqrt(M0)
/home/bartdoekemeijer/python_scripts/floris/floris/simulation/wake_deflection/gauss.py:212: RuntimeWarning: invalid value encountered in sqrt
  ln_deltaDen = (1.6 - np.sqrt(M0)) * (
/home/bartdoekemeijer/python_scripts/floris/floris/simulation/wake_deflection/gauss.py:213: RuntimeWarning: invalid value encountered in sqrt
  1.6 * np.sqrt(sigma_y * sigma_z / (sigma_y0 * sigma_z0)) + np.sqrt(M0)
/home/bartdoekemeijer/python_scripts/floris/floris/simulation/wake_deflection/gauss.py:219: RuntimeWarning: invalid value encountered in sqrt
  * np.sqrt(sigma_y0 * sigma_z0 / (ky * kz * M0))
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 180.00 deg turbulence intensity = 0.060.
   Skipping optimization: outside of wind speed bounds.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 210.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 240.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 270.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 300.00 deg turbulence intensity = 0.060.
  Computing optimal yaw angles for wind speed = 8.00 m/s,  wind direction = 330.00 deg turbulence intensity = 0.060.
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0
            Iterations: 1
            Function evaluations: 3
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.088010003776945
            Iterations: 1
            Function evaluations: 4
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0880100037769445
            Iterations: 1
            Function evaluations: 4
            Gradient evaluations: 1
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0187704706878347
            Iterations: 4
            Function evaluations: 12
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.0
            Iterations: 3
            Function evaluations: 9
            Gradient evaluations: 3
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.1643633813918597
            Iterations: 4
            Function evaluations: 20
            Gradient evaluations: 4
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.164341078402613
            Iterations: 4
            Function evaluations: 20
            Gradient evaluations: 4
==========================================
Total Power Gain = 
Case [0]: wd = 0.00 deg. Gain: 8.801 %
Case [1]: wd = 30.00 deg. Gain: 0.000 %
Case [2]: wd = 60.00 deg. Gain: 0.000 %
Case [3]: wd = 90.00 deg. Gain: 16.436 %
Case [4]: wd = 120.00 deg. Gain: 0.000 %
Case [5]: wd = 150.00 deg. Gain: 0.000 %
Case [6]: wd = 180.00 deg. Gain: 8.801 %
Case [7]: wd = 210.00 deg. Gain: 0.000 %
Case [8]: wd = 240.00 deg. Gain: 1.877 %
Case [9]: wd = 270.00 deg. Gain: 16.434 %
Case [10]: wd = 300.00 deg. Gain: 0.000 %
Case [11]: wd = 330.00 deg. Gain: 0.000 %
==========================================
==========================================
Total time spent: 2.40 s
==========================================
```
Considering the simplicity of this PR, I foresee no problems with `mpi4py` but have not yet tested it. I would like to ask @ejsimley to verify this with one of his Eagle cases.

### CODE REVIEW

**Comment by paulf81** [comment]
Looks good to me!

**Review by ejsimley — APPROVED** [review]
Hey Bart, this looks good to me, thanks!

**Comment by Bartdoekemeijer** [comment]
@bayc can you check this and pull this in? Thanks!

**Review by bayc — APPROVED** [review]

**Comment by bayc** [comment]
> @bayc can you check this and pull this in? Thanks!

@Bartdoekemeijer Looks good, thanks Bart!

**Pull request merged**
