### PR TITLE
Remove "gauss_legacy" wake model

### PR DESCRIPTION
**Pull request by paulf81**
**Feature or improvement description**
Removing the `gauss_legacy` wake model from FLORIS.

### CODE REVIEW

**Comment by rafmudaf** [comment]
@paulf81 I see there's a new folder `historic_versions` containing a couple of Gaussian wake models including `gauss_legacy`. These will always be available in older versions of FLORIS via GitHub and git. Is there a good reason to keep these in the source code? My thought is that this doesn't add much in functionality but it does takeaway clarity in the repository. For example, whats the difference in these two models of the same name:
- https://github.com/NREL/floris/blob/develop/floris/simulation/wake_velocity/gaussianModels/gauss.py
- https://github.com/NREL/floris/blob/develop/floris/simulation/wake_velocity/gaussianModels/historic_versions/gauss.py

**Review by rafmudaf — APPROVED** [review]

**Comment by paulf81** [comment]
@rafmudaf I have had second thoughts on this branch and might close it, we can discuss

**Comment by rafmudaf** [comment]
Ok I'll make it a draft PR for now

**Comment by rafmudaf** [comment]
@paulf81 Is it ok to close this pull request without merging?

**Pull request closed without merging**
