### PR TITLE
BugFix: Avoid negative square root in Cumulative Curl model

### PR DESCRIPTION
**Pull request by paulf81**
Ready to be merged

**Feature or improvement description**
preventing negative sqrts that produce NANs in the cumulative model (original submission by @bayc )

**Related issue, if one exists**
Was included in pull request #392 but handling separately here for neatness

**Impacted areas of the software**
Cumulative curl model

**Test results, if applicable**
Ran examples using cc model without problem

### CODE REVIEW

**Review by rafmudaf — APPROVED** [review]
This is great, thanks @paulf81

**Comment by rafmudaf** [comment]
@bayc should this go to the `main` branch as a bug fix or ok to go to `develop`?

**Comment by bayc** [comment]
@rafmudaf Yea, main makes sense! I'll merge and then back-merge to develop.

**Comment by rafmudaf** [comment]
You'll have to do some cherry picking

**Pull request merged**
