### PR TITLE
Add a fix to inner_power that removes tiny wiggles

### PR DESCRIPTION
**Pull request by paulf81**
This could be ready to merge

**Feature or improvement description**
This fix is meant to address the problem in Issue #554 (and I think along with it discussion #583).  The non-flat region 3 causes odd behaviors in the optimization.  I think one way we can address them is by removing very small changes in the inner_power at the time the turbine class is instantiated.

**Related issue, if one exists**
Issue #554 
Discussion #583 

**Impacted areas of the software**
turbine.py

**Test results, if applicable**
If you now re-run the example 18_check_turbine.py as in Issue #554 , the small perturbations in power are not there

### CODE REVIEW

**Comment by rafmudaf** [comment]
@paulf81 I support including a correction to the power curve such as this, but I'll push back on including this within `floris.simulation`. In general, I'd like to keep these types of changes to user-input at the outer-most level of the code, so I suggest to incorporate this into the `floris.tools` instead. The `simulation` package should strive to remain as general purpose as possible.

That being said, it's not immediately clear where this would fit in the current `floris.tools`, but it might have a role in the `floris.turbine_library`. Overall, I think this should be considered in upcoming work on user interface improvements instead. In that regard, I suggest to reopen #554 and close this pull request.

**Comment by misi9170** [comment]
@paulf81 @rafmudaf An option could be to include it in turbine_utilities.py, which doesn't exist on the main or develop branches but is in the pull request #729 . However, #729 may also not have a place with planned developments of turbine.py.

**Comment by rafmudaf** [comment]
@misi9170 I like that suggestion as it starts to build a library around dealing with turbine inputs.

One workflow might be to do a preprocessing step where the power curve is smoothed and exported either as a new turbine input file or a turbine dictionary for use in the rest of the script. Something along the lines of the code below.

```python
import floris.turbine_library as turbine_library
from floris.tools import FlorisInterface

fi = FlorisInterface(...)

# Show the wiggles
turbine_library.plot_power_curve(fi.turbine[0])

# Smooth the wiggles
corrected_turbine = turbine_library.turbine_utilities.smooth_power_curve(fi.turbine[0])
# Question: what is the type of corrected_turbine - Turbine or dict?

# Show that they're smoothed
turbine_library.plot_power_curve(corrected_turbine)

# Put this back into the simulation object
fi.reinitialize(turbine_type=corrected_turbine)
```

**Comment by paulf81** [comment]
I agree with all of this, and I think putting this correction as something to be more sensibly included in a re-worked turbine workflow, rather than forced into simulation.py will work great for me.  Would you like me then to close this pull request @rafmudaf ?  And re-open #554 ?

**Comment by Bartdoekemeijer** [comment]
To fundamentally resolve this, would it make sense to replace the power coefficient table in the turbine input file by an absolute power table? This would be a cleaner solution than adding some kind of smoothing function.

**Comment by paulf81** [comment]
Great minds think alike!  This is the proposal for 4.0, and agree this is a simpler solution

**Pull request closed without merging**
