### PR TITLE
Add match example

### PR DESCRIPTION
**Pull request by paulf81**
Adding back in example 20 (plus documentation) showing how to make FLORIS match a given SOWFA layout in the latest style convention

### CODE REVIEW

**Comment by bayc** [comment]
Yea, looks good to me as well!

**Comment by nhamilto** [comment]
Looks good to me too.

**Comment by nhamilto** [comment]
wrong button...

**Comment by paulf81** [comment]
Ok, I'm merging, the CI is saying that the documentation has an error, but I'm thinking this is just because it's a work in progress

**Pull request merged**
