### PR TITLE
Add GH Action to ensure examples run

### PR DESCRIPTION
**Pull request by rafmudaf**
**Feature or improvement description**
Adds a GitHub Actions workflow to ensure that all of the Python files (`.py` extension) in `floris/examples/` will execute successfully. This does not check any of the output for correctness.

**Related issue, if one exists**
See comments in #405

**Impacted areas of the software**
Automated testing

**Additional supporting information**
Note that currently an example does not run correctly so this fails. See it live at https://github.com/rafmudaf/floris/actions/runs/2093234885

### CODE REVIEW

**Comment by rafmudaf** [comment]
All right sorry for all the spam you may have gotten from GitHub while I made changes to this pull request. This Action now runs all examples except the ones requiring additional dependencies (11 - pyOptSparse, 16 - Streamlit). It also reports the failing examples at the end so that its not lost in all of the output from the examples:

```
Error in example:
[536](https://github.com/rafmudaf/floris/runs/5836089968?check_suite_focus=true#step:5:536)
 - 07_calc_aep_from_rose.py
```

**Comment by rafmudaf** [comment]
Note this does not run the Jupiter notebook (Example 00).

**Comment by rafmudaf** [comment]
Nice idea @Bartdoekemeijer, I've added this feature

**Comment by paulf81** [comment]
This is such a great idea, thank you @rafmudaf !!!

**Comment by rafmudaf** [comment]
Ok @Bartdoekemeijer the Notebook conversion to Python script is in place and reporting correctly. This could use a little polish down the road but it works just fine, at the moment.

**Comment by rafmudaf** [comment]
Detail details details. Nearly there!

**Comment by Bartdoekemeijer** [comment]
Looks great!!

**Comment by rafmudaf** [comment]
There are still issues with running the notebook, but I've mostly worked it out.

**Pull request merged**
