### PR TITLE
Modularize calculate_wake enabling additional wake/farm solvers

### PR DESCRIPTION
**Pull request by bayc**
**Complete this sentence**
THIS PULL REQUEST __IS NOT__ READY TO MERGE

**Feature or improvement description**
This pull request contains an initial implementation of modularizing calculate wake to support different solvers than the standard, sequential turbine solver built into FLORIS. This pull request also contains an implementation of a cumulative Gaussian wake model, detailed in: Bastankhah, Majid, et al. "Analytical solution for the cumulative wake of wind turbines in wind farms." arXiv preprint [arXiv:2011.00894](https://arxiv.org/abs/2011.00894) (2020).

**Related issue, if one exists**
None.

**Impacted areas of the software**
`floris/simulation/flow_field.py`
`floris/simulation/wake.py`
`floris/simulation/farm.py`
`floris/simulation/wake_velocity/gaussianModels/gauss_cumulative.py`

**Additional supporting information**
None.

**Test results, if applicable**
Need to update/add tests to reflect new software structure.

### CODE REVIEW

**Comment by bayc** [comment]
**TODO:**

- [ ] Create `floris_interface` method for selecting/setting solver
- [ ] Implement checking for valid model/solver combinations
- [ ] Verify documentation is up-to-date with changes
- [ ] Add tests for new `flow_field` methods

**Comment by paulf81** [comment]
Is it possible a file called "wake_solver" is missing, I'm currently getting an error:

```
Traceback (most recent call last):
  File "compare_gauss_cumulative.py", line 19, in <module>
    import floris.tools as wfct
  File "/Users/pfleming/Desktop/git_tools/FLORIS/floris/__init__.py", line 64, in <module>
    from . import tools, utilities, simulation, logging_manager
  File "/Users/pfleming/Desktop/git_tools/FLORIS/floris/tools/__init__.py", line 39, in <module>
    from . import (
  File "/Users/pfleming/Desktop/git_tools/FLORIS/floris/tools/floris_interface.py", line 26, in <module>
    from floris.simulation import Floris, Turbine, WindMap, TurbineMap
  File "/Users/pfleming/Desktop/git_tools/FLORIS/floris/simulation/__init__.py", line 39, in <module>
    from . import (
ImportError: cannot import name 'wake_solver' from 'floris.simulation' (/Users/pfleming/Desktop/git_tools/FLORIS/floris/simulation/__init__.py)
(floris) pfleming-32008s:compare_models pfleming$ 
```

**Comment by bayc** [comment]
@paulf81 Yea, a whole sub-directory is missing. Let me track down what happened.

**Comment by bayc** [comment]
@paulf81 Yep, subdirectory/files were untracked and I forgot to add them. Give it a go now!

**Comment by rafmudaf** [comment]
@bayc Will this pull request be merged into FLORIS v2 or is this replaced by v3?

**Pull request closed without merging**
