### PR TITLE
Continuous secondary steering

### PR DESCRIPTION
**Pull request by pjstanle**
**Complete this sentence**
THIS PULL REQUEST __IS NOT__ READY TO MERGE

**Feature or improvement description**
Make the yaw correction term for secondary wake steering continuous with an interpolation. This is accomplished by finding the intersection of two lines determined by the closest, discrete yaw values that would reproduce the same average spanwise velocity.

**Related issue, if one exists**
None.

**Impacted areas of the software**
Anything with wake steering and GCH.

**Additional supporting information**
None.

**Test results, if applicable**
The regression test values for the gch_baseline and secondary_steering cases have been updated..

### CODE REVIEW

**Comment by paulf81** [comment]
Hi @pjstanle , I downloaded and confirm it works, to check for change behaviors I ran the example five_turbine.py in:
/Users/pfleming/Desktop/git_tools/FLORIS/examples/gch_comparisons/five_turbine

And added print statement to line 169:
print(result) and get:

Develop:
[1.         1.42254026 1.1798154  1.1798154 ]
[1.         1.10888021 1.46037838 1.21079757]
[1.         1.04625117 1.17825305 1.48001324]
[1.         1.03276177 1.1106778  1.26927153]
[1.         1.03621731 1.09204541 1.12964519]

Continuous_secondary:
[1.         1.42254703 1.179821   1.179821  ]
[1.         1.10699732 1.45967207 1.21021432]
[1.         1.04541969 1.17529514 1.4799997 ]
[1.         1.03122265 1.11064111 1.27115566]
[1.         1.03550961 1.09142024 1.12987479]

These are trivial changes so I think really fine but just to check, does it match your expectation?

**Comment by bayc** [comment]
@paulf81 I spoke with @jrannoni about the differences in power they she agreed they seemed reasonable.

@pjstanle I added some documentation/did some reorganizing of the code. Would you make sure you agree with everything?

**Comment by paulf81** [comment]
> @paulf81 I spoke with @jrannoni about the differences in power, she agreed they seemed reasonable.
> 
> @pjstanle I added some documentation/did some reorganizing of the code. Would you make sure you agree with everything?
> 
> * [ ]  update regression tests with new values

This makes sense to me Chris, thanks checking!  And now I realize I'm being redundant to regression checks but thanks for checking!

**Comment by pjstanle** [comment]
@paulf81 Yes these changes make sense, some go up slightly and some go down slightly as the effective yaw angle change up or down a tiny bit from making it continuous. 
@bayc the clarifications look good!

**Review by bayc — APPROVED** [review]

**Pull request merged**
