### PR TITLE
Feature: Updating "rotate_coordinates_rel_west" function in utilities to fix farm orientation for plots

### PR DESCRIPTION
**Pull request by MYMahfouz**
**Feature or improvement description**
Fixing the farm orientation before plotting, this pull request builds on the work done in an earlier pull request: https://github.com/NREL/floris/pull/533

**Related issue, if one exists**
This pull request builds on the work done in an earlier pull request: https://github.com/NREL/floris/pull/533
Fix orientation: https://github.com/NREL/floris/discussions/348, https://github.com/NREL/floris/issues/357, https://github.com/NREL/floris/issues/372
non-matching plot turbine with fi: https://github.com/NREL/floris/issues/448, https://github.com/NREL/floris/issues/451, https://github.com/NREL/floris/discussions/455, https://github.com/NREL/floris/pull/512

**Impacted areas of the software**
utilities.py: fn rotate_coordinates_rel_west() adding 2 parameters (farm layout_x and layout_y)
florice_interface.py: updated calling rotate_coordinates_rel_west() within get_plane_of_points()
There other changes that I got from https://github.com/NREL/floris/pull/533
fix orientation
v grid.py: class flowfiledplanar Grid method set_grid (Braoden flowfield, rotate mesh grid)
v utilities.py: ftn rotate_coordinates_rel_west() adding 1 parameter (inv_rot)
v floris_interface.py: method get_plane_of_points() (reverse rotating to north up)

**Additional supporting information**

**Test results, if applicable**

### CODE REVIEW

**Comment by rafmudaf** [comment]
@MYMahfouz Just heads up that I updated this branch and placed it (via `git-rebase`) on top of develop.

**Comment by bayc** [comment]
Hello, I believe this functionality has been integrated into some other work in #578. It would be great if you are able to check and verify that it does provide the same functionality you were aiming for here.

**Comment by misi9170** [comment]
> Hello, I believe this functionality has been integrated into some other work in #578. It would be great if you are able to check and verify that it does provide the same functionality you were aiming for here.

See also #641

**Comment by rafmudaf** [comment]
I'm closing this pull request since I think it is covered by #578 and #650 like @bayc and @misi9170 mentioned above. @MYMahfouz please update or reopen if this has been incorrectly closed.

**Pull request closed without merging**
