### PR TITLE
Develop MIT Yaw Loss model in V4

### PR DESCRIPTION
**Pull request by paulf81**
# Develop MIT Yaw Loss model in V4

This draft PR/branch is meant to collaboratively develop the MIT yaw loss model into the v4 framework.

This pull request should take over for PR #638 as this works much better in the v4 framework than in v3.

## Related issue

Issue #624 
Pull request #638

### CODE REVIEW

**Comment by paulf81** [comment]
@misi9170 , was hoping to get a quick check from you that this all looks like a reasonable starting point

**Comment by misi9170** [comment]
> @misi9170 , was hoping to get a quick check from you that this all looks like a reasonable starting point

Looks good! I made a minor change to the example and then added a placeholder for testing the new operation model. The tests are currently based on the `CosineLossTurbine`, so may start failing as the actual `MITLossTurbine` code is implemented. That's fine; the tests should then be updated to reflect the actual expected behavior. I'm happy to help with that.

**Comment by paulf81** [comment]
> > @misi9170 , was hoping to get a quick check from you that this all looks like a reasonable starting point
> 
> Looks good! I made a minor change to the example and then added a placeholder for testing the new operation model. The tests are currently based on the `CosineLossTurbine`, so may start failing as the actual `MITLossTurbine` code is implemented. That's fine; the tests should then be updated to reflect the actual expected behavior. I'm happy to help with that.

Sounds great, thank you!

**Comment by paulf81** [comment]
Closing as replace by #924

**Pull request closed without merging**
