### PR TITLE
Add arbitrary flow field point probing support

### PR DESCRIPTION
**Pull request by paulf81**
Not yet ready to merge

# Add ability to get velocity at arbitrary points

This branch, based on the branch on @rafmudaf adds the ability to collect the velocity at arbitrary points in space, based on the the new PointsGrid class.  The feature is meant to be similar in some ways to visualization methods, but avoids duplicate calls to underlying turbine grid solvers such that adding a few test points should not substantially slow down computation as adding a whole plane of points would.  

Further, the method seems to enable simplification of the code in that other visualization methods could be converted to be effectively wrappers to this call passed in differently oriented planes of points, or even volumes.

Currently also includes 3-4 additional examples but this number may change as we get nearer a final version.  

Still to go:

- [ ] Resolve issue that turbines apparently move when wind direction changes
- [ ] Add examples to directly test that wake is where we'd think by using farm layouts more complicated than lines
- [ ] Confirm works with at least most models (GCH/empirical/Jensen)
- [ ] Convert planar visualizations to be wrappers?
- [ ] Clean up things

### CODE REVIEW

**Comment by paulf81** [comment]
@misi9170  in your email you mentioned you might have a little reconciliation to go with the work of @bayc  and @Bartdoekemeijer , just wanted to check if that is included in the commit above, or if I should wait?  thanks!

**Comment by paulf81** [comment]
> > @misi9170 in your email you mentioned you might have a little reconciliation to go with the work of @bayc and @Bartdoekemeijer , just wanted to check if that is included in the commit above, or if I should wait? thanks!
> 
> @paulf81 Thanks for making a note of that. Those reconciliations are _not_ currently included. Just to record our discussion from earlier, let's plan to get the other PR (#578) into develop first; then I'll merge develop and deal with the merge conflicts. @bayc did a bit of work on #578 this morning to make sure it'll be ready to accept this PR with minimal changes.

Sounds great, thank you!

**Comment by misi9170** [comment]
> @paulf81 @misi9170 is this ready for review? If so, please change it from "draft" to "ready for review". Also, the tests are failing so that should be addressed asap.

Thanks @rafmudaf. I'll look into this now and provide an update shortly.

**Comment by misi9170** [comment]
This pull request has now been replaced by #650.

**Comment by rafmudaf** [comment]
Replaced by #650

**Pull request closed without merging**
