### PR TITLE
Feature: farm orientation Fix(north up) and matching plot turbine with fi

### PR DESCRIPTION
**Pull request by dhcho347**
**Feature or improvement description**

1. Fix farm orientation(or north up, do not rotating to west)
2. matching plot_turbine_with_fi
3. enhence. plot_turbine_with_if (to consider the shape change issue of farm.rotor_diameters after claculate_wake)
- details: #530 
image

**Related issue, if one exists**

Fix orientation: #348, #357, #372
non-matching plot turbine with fi: #448, #451, #455, #512
 
**Impacted areas of the software**

1. fix orientation
v grid.py: class flowfiledplanar Grid method set_grid (Braoden flowfield, rotate mesh grid)
v utilities.py:  ftn rotate_coordinates_rel_west() adding 1 parameter (inv_rot)
v floris_interface.py: method get_plane_of_points() (reverse rotating to north up)
2. matching plot turbine with fi
v visualization.py: ftn plot_turbines_with_fi, plot_turbines

**Additional supporting information**

**Test results, if applicable**

### CODE REVIEW

**Comment by dhcho347** [comment]
There were 1 conflicting file (visualization.py)
Since I used to fork the main branch, I changed the conflicting visualization.py file to one in the develop branch and 
modified it again.
Is it better to fork the develop branch and work on it?

**Comment by rafmudaf** [comment]
> Since I used to fork the main branch, I've changed the conflicting visualization.py file to one in the develop branch and
> modified it again.
> Is it better to fork the develop branch and work on it?

Hi @dhcho347 Yes, its best to work from the develop branch. As far as I can tell, you've done the git workflow correctly.

**Comment by dhcho347** [comment]
Hi, @rafmudaf,
I worked again with the **develop branch.** 
(There is a change in Floris_interface.py: get_turbine_velocities -> turbine_average_velocities)

How can I change this pull request with new one (fromDevelop branch)?

**Comment by rafmudaf** [comment]
Hi @dhcho347 I rebased this branch onto `develop` and force-pushed so that I am able to separate only the changes that you've made from any changes from your initial branch off of main. Just wanted to give you a heads up. You can update your local branch with these commands:
```bash
git fetch
git checkout visual_chk

# Optional: if you have any uncommitted changes, stash them and we'll reapply them later
git stash

# Check <remote> to the name of your repository in your local repository
git reset --hard <remote> visual_chk

# Optional: if you stashed changes, reapply them
# Note that you may have merge conflicts to resolve at this point
git stash pop
```

**Comment by rafmudaf** [comment]
@dhcho347 My apologies for all the noise here.

**Comment by rafmudaf** [comment]
I believe this is superseded by #578 and #633. See https://github.com/NREL/floris/discussions/530#discussioncomment-6347156.

**Pull request closed without merging**
